### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by vorburger** [poser55/linked-db-rows#4]
Cool project! But it's not clear under which license you are making this code available... am I allowed to use it? Under what conditions?

Thou shall ALWAYS [choose a license](https://choosealicense.com)... 😈

**Comment by vorburger** [comment]
Oh, https://github.com/poser55/linked-db-rows/blob/3c0bfee51cddc7cd2db0bb80687125f5bca832ac/README.md#license 

ergo #5

**Comment by poser55** [comment]
Just added a license:
https://github.com/poser55/linked-db-rows/blob/master/LICENSE
